### ISSUE TITLE
MojoModel.load() error: Exception in thread "main" java.lang.NullPointerException: entry

### ISSUE THREAD

**Issue by kevin-wzh** [h2oai/h2o-3#15721]
hi，I'm through MojoModel.load("drf_70f76f68_29a9_436b_965d_731013a61817.zip") method to model load operation, but there is a mistake: the Exception in the thread "is the main" Java. Lang. NullPointerException: entry

**The code is as follows：**

```
import java.io.*;
import hex.genmodel.easy.RowData;
import hex.genmodel.easy.EasyPredictModelWrapper;
import hex.genmodel.easy.prediction.*;
import hex.genmodel.MojoModel;

public class main {
  public static void main(String[] args) throws Exception {

    EasyPredictModelWrapper model = new EasyPredictModelWrapper(MojoModel.load("drf_70f76f68_29a9_436b_965d_731013a61817.zip"));

    RowData row = new RowData();
    row.put("AGE", "68");
    row.put("RACE", "2");
    row.put("DCAPS", "2");
    row.put("VOL", "0");
    row.put("GLEASON", "6");

    BinomialModelPrediction p = model.predictBinomial(row);
    System.out.println("Has penetrated the prostatic capsule (1=yes; 0=no): " + p.label);
    System.out.print("Class probabilities: ");
    for (int i = 0; i < p.classProbabilities.length; i++) {
      if (i > 0) {
    System.out.print(",");
      }
      System.out.print(p.classProbabilities[i]);
    }
    System.out.println("");
  }
}
```

**Example：**
I have imported the model file and h2o-genmodel.jar file locally。

`javac -cp h2o-genmodel.jar -J-Xms2g -J-XX:MaxPermSize=128m main.java`

`java -cp .:h2o-genmodel.jar main`

**Comment by mn-mikke** [comment]
Hi @kevin-wzh,
can you share the stack trace of the exception?

**Comment by kevin-wzh** [comment]
**I changed the java version of this problem, and now it can run, but I used python to load the model times error as follows:**

```
Traceback (most recent call last):
  File "/Users/bc_aqr/Desktop/work/Project/ModelInfer/0905.py", line 75, in <module>
    model = h2o.load_model("/Users/bc_aqr/Desktop/work/Project/ModelInfer/DRF_model_python_1693534623102_1.zip")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h2o/h2o.py", line 1579, in load_model
    res = api("POST /99/Models.bin/%s" % "", data={"dir": path})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h2o/h2o.py", line 122, in api
    return h2oconn.request(endpoint, data=data, json=json, filename=filename, save_to=save_to)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h2o/backend/connection.py", line 499, in request
    return self._process_response(resp, save_to)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h2o/backend/connection.py", line 853, in _process_response
    raise H2OResponseError(data)
h2o.exceptions.H2OResponseError: Server error java.lang.IllegalArgumentException:
  Error: Missing magic number 0x1CED at stream start
  Request: POST /99/Models.bin/
    data: {'dir': '/Users/bc_aqr/Desktop/work/Project/ModelInfer/DRF_model_python_1693534623102_1.zip'}
```




Use as follows：
`model = h2o.load_model("/Users/bc_aqr/Desktop/work/Project/ModelInfer/DRF_model_python_1693534623102_1.zip")`

However, the way I use
`model = h2o.import_mojo("/Users/bc_aqr/Desktop/work/Project/ModelInfer/DRF_model_python_1693534623102_1.zip")`
It can be used normally. But I want my service to support more model loads, so far I can only upload mojo models

**Comment by mn-mikke** [comment]
Closing the issue for now, if there is something unclear please reopen.

**Comment by kevin-wzh** [comment]
Thank you, I will follow the link you gave to read！
