### ISSUE TITLE
Coefficient Constraint check on intercept - GLM

### ISSUE THREAD

**Issue by srideviparise1** [h2oai/h2o-3#15892]
When running GLM train, I get the following error:

water.exceptions.H2OFailException: GLM model coefficient-1.3907771259050355E-6 exceeds beta constraint bounds.  Lower: 0.0, upper: Infinity
        at hex.glm.GLM$GLMDriver.checkCoeffsBounds(GLM.java:3104)
        at hex.glm.GLM$GLMDriver.doCompute(GLM.java:3035)
        at hex.glm.GLM$GLMDriver.computeImpl(GLM.java:2884)
        at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:252)
        at hex.glm.GLM$GLMDriver.compute2(GLM.java:1492)
        at water.H2O$H2OCountedCompleter.compute(H2O.java:1677)
        at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
        at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:976)
        at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)Closing connection _sid_bcf3 at exit

Looks like the intercept is being also tested for the non_negative constraint. I do see a previous issue on this:

https://github.com/h2oai/h2o-3/commit/64fae7f3296a4b67c7cdb57561f6be7e0d5bc98c

not sure this was merged.

I am using 3.38.0.4 but I see master branch also has same issue. Thanks.

**Comment by wendycwong** [comment]
Hi @srideviparise1:

I checked the constraint code, the intercept level is set to -Infinity to Infinity.  So, even though it is checked, it should never throw an error.  Can you share your code so I can reproduce and fix?  Thanks, W

**Comment by srideviparise1** [comment]
Ah, maybe its not the intercept then. Let me get you the minimum reproducible code/dataset. In the meantime, is it possible for other learned coefficients to not satisfy the (non_negative = True) constraint? Thanks.

**Comment by wendycwong** [comment]
If the code is implemented correctly, there should not be any possibility that learned coefficients violate the beta_constraints / non_negative constraints.  If you find anything that is not true, please send me the code to reproduce so I can fix the bug.  Thanks, W

**Comment by wendycwong** [comment]
I am closing this issue.  Please open a new one if you find another problem.
