### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by projetosfsi** [h2oai/h2o-3#16314]
**H2O version, Operating System and Environment**
Ubuntu 22.04 or Ubuntu 20.04 in WLS
No Firewall
No AntiVirus
Python 3.10
Java Version: 
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

**Actual behavior**
I have a project that I have been using since 2023.

In it I make the h20 call this way

# Check if H2O is running and close it if it is
if h2o.connection():
 h2o.cluster().shutdown()

# Initialize the H2O server
h2o.init(max_mem_size="20G") # Limit memory usage by H2O

This has always worked for me, however I recently reinstalled the system and am resuming my project. When installing h20 in the latest version I cannot connect, I went back to previous versions and the error persists.

Has anything changed in H2O?

Is there any BUG with WSL2?

In some logs it showed that it was trying to connect to 10.255.255.254 trying to use the same port as the H20

**Expected behavior**
Found H2O

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):

1. Create a python script that your H20 AutoML
2. Try to run it and you will get an error

**Upload logs**
03:04:25.704 [main] INFO  hex.tree.xgboost.util.NativeLibrary - Loaded library from lib/linux_64/libxgboost4j_gpu.so (/tmp/libxgboost4j_gpu8751395465772505637.so)
06-29 03:04:25.931 127.0.0.1:54321       11355        main  INFO water.default: ----- H2O started  -----
06-29 03:04:25.932 127.0.0.1:54321       11355        main  INFO water.default: Build git branch: rel-3.46.0
06-29 03:04:25.932 127.0.0.1:54321       11355        main  INFO water.default: Build git hash: e951137a01b24a224c182c5eacbad871e0184d4e
06-29 03:04:25.932 127.0.0.1:54321       11355        main  INFO water.default: Build git describe: jenkins-3.46.0.2-12-ge951137a01b
06-29 03:04:25.933 127.0.0.1:54321       11355        main  INFO water.default: Build project version: 3.46.0.3
06-29 03:04:25.933 127.0.0.1:54321       11355        main  INFO water.default: Build age: 17 days
06-29 03:04:25.933 127.0.0.1:54321       11355        main  INFO water.default: Built by: 'jenkins'
06-29 03:04:25.933 127.0.0.1:54321       11355        main  INFO water.default: Built on: '2024-06-11 16:51:15'
06-29 03:04:25.934 127.0.0.1:54321       11355        main  INFO water.default: Found H2O Core extensions: [XGBoost, KrbStandalone, Infogram]
06-29 03:04:25.934 127.0.0.1:54321       11355        main  INFO water.default: Processed H2O arguments: [-ip, 127.0.0.1, -web_ip, 127.0.0.1, -baseport, 54321, -ice_root, /tmp/tmph6muvm49, -name, H2O_from_python_root_d7ia2e, -log_level, INFO, -allow_unsupported_java]
06-29 03:04:25.934 127.0.0.1:54321       11355        main  INFO water.default: Java availableProcessors: 12
06-29 03:04:25.935 127.0.0.1:54321       11355        main  INFO water.default: Java heap totalMemory: 480.0 MB
06-29 03:04:25.935 127.0.0.1:54321       11355        main  INFO water.default: Java heap maxMemory: 20.00 GB
06-29 03:04:25.936 127.0.0.1:54321       11355        main  INFO water.default: Java version: Java 11.0.23 (from Ubuntu)
06-29 03:04:25.936 127.0.0.1:54321       11355        main  INFO water.default: JVM launch parameters: [-ea, -Xmx20G]
06-29 03:04:25.936 127.0.0.1:54321       11355        main  INFO water.default: JVM process id: 11355@PCRyzen
06-29 03:04:25.937 127.0.0.1:54321       11355        main  INFO water.default: OS version: Linux 5.15.153.1-microsoft-standard-WSL2 (amd64)
06-29 03:04:25.937 127.0.0.1:54321       11355        main  INFO water.default: Machine physical memory: 29.38 GB
06-29 03:04:25.937 127.0.0.1:54321       11355        main  INFO water.default: Machine locale: en
06-29 03:04:25.937 127.0.0.1:54321       11355        main  INFO water.default: X-h2o-cluster-id: 1719641064283
06-29 03:04:25.938 127.0.0.1:54321       11355        main  INFO water.default: User name: 'root'
06-29 03:04:25.938 127.0.0.1:54321       11355        main  INFO water.default: IPv6 stack selected: false
06-29 03:04:25.938 127.0.0.1:54321       11355        main  INFO water.default: Possible IP Address: eth0 (eth0), fe80:0:0:0:215:5dff:fed4:efa1%eth0
06-29 03:04:25.939 127.0.0.1:54321       11355        main  INFO water.default: Possible IP Address: eth0 (eth0), 172.29.160.217
06-29 03:04:25.939 127.0.0.1:54321       11355        main  INFO water.default: Possible IP Address: lo (lo), 0:0:0:0:0:0:0:1%lo
06-29 03:04:25.939 127.0.0.1:54321       11355        main  INFO water.default: Possible IP Address: lo (lo), 10.255.255.254
06-29 03:04:25.939 127.0.0.1:54321       11355        main  INFO water.default: Possible IP Address: lo (lo), 127.0.0.1
06-29 03:04:25.940 127.0.0.1:54321       11355        main  INFO water.default: Selected H2O.CLOUD_MULTICAST_IF: name:lo (lo) doesn't support multicast
06-29 03:04:25.945 127.0.0.1:54321       11355        main  INFO water.default: H2O node running in unencrypted mode.
06-29 03:04:25.947 127.0.0.1:54321       11355        main  INFO water.default: Internal communication uses port: 54322
06-29 03:04:25.947 127.0.0.1:54321       11355        main  INFO water.default: Listening for HTTP and REST traffic on http://127.0.0.1:54321/
06-29 03:04:25.948 127.0.0.1:54321       11355        main  INFO water.default: H2O cloud name: 'H2O_from_python_root_d7ia2e' on /127.0.0.1:54321, discovery address /239.236.252.147:61420
06-29 03:04:25.949 127.0.0.1:54321       11355        main  INFO water.default: If you have trouble connecting, try SSH tunneling from your local machine (e.g., via port 55555):
06-29 03:04:25.949 127.0.0.1:54321       11355        main  INFO water.default:   1. Open a terminal and run 'ssh -L 55555:localhost:54321 root@127.0.0.1'
06-29 03:04:25.949 127.0.0.1:54321       11355        main  INFO water.default:   2. Point your browser to http://localhost:55555
06-29 03:04:26.677 127.0.0.1:54321       11355        main  INFO water.default: Kerberos not configured
06-29 03:04:26.678 127.0.0.1:54321       11355        main  INFO water.default: Log dir: '/tmp/tmph6muvm49/h2ologs'
06-29 03:04:26.678 127.0.0.1:54321       11355        main  INFO water.default: Cur dir: '/root'
06-29 03:04:26.686 127.0.0.1:54321       11355        main  INFO water.default: Subsystem for distributed import from HTTP/HTTPS successfully initialized
06-29 03:04:26.687 127.0.0.1:54321       11355        main  INFO water.default: HDFS subsystem successfully initialized
06-29 03:04:26.689 127.0.0.1:54321       11355        main  INFO water.default: S3 subsystem successfully initialized
06-29 03:04:26.699 127.0.0.1:54321       11355        main  INFO water.default: GCS subsystem successfully initialized
06-29 03:04:26.699 127.0.0.1:54321       11355        main  INFO water.default: Drive subsystem not available
06-29 03:04:26.700 127.0.0.1:54321       11355        main  INFO water.default: Flow dir: '/root/h2oflows'
06-29 03:04:26.706 127.0.0.1:54321       11355        main  INFO water.default: Cloud of size 1 formed [/127.0.0.1:54321]
06-29 03:04:26.716 127.0.0.1:54321       11355        main  INFO water.default: Registered parsers: [GUESS, ARFF, XLS, SVMLight, AVRO, PARQUET, CSV]
06-29 03:04:26.718 127.0.0.1:54321       11355        main  INFO water.default: XGBoost extension initialized
06-29 03:04:26.720 127.0.0.1:54321       11355        main  INFO water.default: KrbStandalone extension initialized
06-29 03:04:26.720 127.0.0.1:54321       11355        main  INFO water.default: Infogram extension initialized
06-29 03:04:26.720 127.0.0.1:54321       11355        main  INFO water.default: Registered 3 core extensions in: 1369ms
06-29 03:04:26.721 127.0.0.1:54321       11355        main  INFO water.default: Registered H2O core extensions: [XGBoost, KrbStandalone, Infogram]
06-29 03:04:26.725 127.0.0.1:54321       11355        main  INFO hex.tree.xgboost.XGBoostExtension: Found XGBoost backend with library: xgboost4j_gpu
06-29 03:04:26.726 127.0.0.1:54321       11355        main  INFO hex.tree.xgboost.XGBoostExtension: XGBoost supported backends: [WITH_GPU, WITH_OMP]
06-29 03:04:26.974 127.0.0.1:54321       11355        main  INFO water.default: Registered: 288 REST APIs in: 253ms
06-29 03:04:26.974 127.0.0.1:54321       11355        main  INFO water.default: Registered REST API extensions: [Mojo 2 pipeline extensions, XGBoost, Amazon S3, Algos, Infogram, AutoML, Core V3, TargetEncoder, Core V4]
06-29 03:04:27.086 127.0.0.1:54321       11355        main  INFO water.default: Registered: 332 schemas in 111ms
06-29 03:04:27.087 127.0.0.1:54321       11355        main  INFO water.default: H2O started in 2800ms
06-29 03:04:27.087 127.0.0.1:54321       11355        main  INFO water.default: 
06-29 03:04:27.087 127.0.0.1:54321       11355        main  INFO water.default: Open H2O Flow in your web browser: http://127.0.0.1:54321
06-29 03:04:27.087 127.0.0.1:54321       11355        main  INFO water.default: 
06-29 03:04:27.165 127.0.0.1:54321       11355  8420930-32  INFO water.default: GET /3/Metadata/schemas/CloudV3, parms: {}
06-29 03:04:27.173 127.0.0.1:54321       11355  8420930-32  INFO water.default: Locking cloud to new members, because water.api.schemas3.MetadataV3
06-29 03:04:29.819 127.0.0.1:54321       11355   FJ-126-15  INFO water.default: Cloud of size 2 formed [/127.0.0.1:54321, /10.255.255.254:54321]
06-29 03:04:29.874 127.0.0.1:54321       11355  8420930-16  INFO water.default: GET /3/Metadata/schemas/H2OErrorV3, parms: {}
06-29 03:04:29.883 127.0.0.1:54321       11355  8420930-17  INFO water.default: GET /3/Metadata/schemas/H2OModelBuilderErrorV3, parms: {}
06-29 03:04:29.942 127.0.0.1:54321       11355  8420930-19  INFO water.default: POST /4/sessions, parms: {}
06-29 03:04:29.963 127.0.0.1:54321       11355  8420930-14  INFO water.default: POST /99/Rapids, parms: {ast=(setTimeZone "UTC"), session_id=_sid_881d}
06-29 03:04:29.993 127.0.0.1:54321       11355  .254:54321 ERROR water.default: Got IO error when sending a batch of bytes: 
java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:483) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:472) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:692) ~[?:?]
	at water.H2ONode.openChan(H2ONode.java:496) ~[h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.openChan(H2ONode.java:634) ~[h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.sendBuffer(H2ONode.java:608) [h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.run(H2ONode.java:592) [h2o.jar:?]
06-29 03:04:34.998 127.0.0.1:54321       11355  .254:54321 ERROR water.default: Got IO error when sending a batch of bytes:

**Comment by gzzpsxsbrblmd** [comment]
Exactly the same case for me. Is there any work-around?

**Comment by projetosfsi** [comment]
> Exactly the same case for me. Is there any work-around?

I implemented it in docker and changed the port, that was the way I managed to make it work

**Comment by kamilpytlak** [comment]
Same issue here.

**Comment by sxyzy1016** [comment]
Maybe try this: [https://github.com/microsoft/WSL/issues/12170#issuecomment-2419324412](url)
