### ISSUE TITLE
NoClassDefFound exception at water.logging.LoggerFactory

### ISSUE THREAD

**Issue by gjevardat** [h2oai/h2o-3#6725]
Hello

Upgrading from 3.30.x to 3.40.x raises this exception when initialising the water logging class in my client java application:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Priority
```
I see in the code that only ClassNotFound is caught but not NoClassDefFound
```
 private boolean isWaterLogAvailable() {
        try {
            Class.forName(waterLogClassName);
            return true;
        } catch (ClassNotFoundException e) {
            return false;
        }
    }
```
Indeed in my class path I use only log4j2 libraries so I do not have 

Probably I missed something while upgrading, but how could I force my client not to use water logging system. I'd like to use only log4j2 as in 3.30x. More precisely I don't want to depend on log4j 1 versions...

Thanks for help

**Comment by yazun** [comment]
We have the same issue. Looks like only adding water as dependency could resolve it as long as this bug is not fixed?

**Comment by yazun** [comment]
This is happening when we are just trying to load DRF, with no water dependecies needed. It works ok for XGB i.e.
```java
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [gaia.cu7.algo.classification.supervised.ClassificationTaker]: Factory method 'classificationTaker' threw exception; nested exception is java.lang.NoClas
sDefFoundError: org/apache/log4j/Priority
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 47 more
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Priority
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at water.logging.LoggerFactory.isWaterLogAvailable(LoggerFactory.java:79)
        at water.logging.LoggerFactory.<init>(LoggerFactory.java:19)
        at water.logging.LoggerFactory.<clinit>(LoggerFactory.java:7)
        at hex.genmodel.algos.tree.SharedTreeMojoModel.<clinit>(SharedTreeMojoModel.java:30)
        at java.base/java.lang.Class.forName0(Native Method)
```

**Comment by yazun** [comment]
Thanks a lot!
